language:
  - bash

services:
  - docker

sudo: true

jobs:
  include:
    - stage: build
      script: ./ci/bin/docker_build_and_push.sh 11 node:11 node:11.12 node:11.12.0-stretch
    - stage: build
      script: ./ci/bin/docker_build_and_push.sh 11/java node:java node:11-java node:11.12-java node:11.12.0-java

