on: [push]

name: Build Docker images

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: '${{ secrets.DOCKER_PASSWORD }}'
  DOCKER_ORGANIZATION: philipssoftware
  GITHUB_ORGANIZATION: philips-software

jobs:
  build_node_12:
    name: Build node 12
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - name: Build Docker Images with node
      uses: philips-software/docker-ci-scripts@v3.3.2
      with:
        dockerfile: 12/vanilla
        image-name: node
        tags: 12 12.22 12.22.7 12.22.7-buster
        push-branches: main
  
  build_node_12_java:
    name: Build node 12 java
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - name: Build Docker Images with node and java
      uses: philips-software/docker-ci-scripts@v3.3.2
      with:
        dockerfile: 12/java
        image-name: node
        tags: 12-java 12.22-java 12.22.7-java 12.22.7-buster-slim-java
        push-branches: main

  build_node_14:
    name: Build node 14
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - name: Build Docker Images with node
      uses: philips-software/docker-ci-scripts@v3.3.2
      with:
        dockerfile: 14/vanilla
        image-name: node
        tags: 14 14.18 14.18.1 14.18.1-buster
        push-branches: main

  build_node_14_java:
    name: Build node 14 with java
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - name: Build Docker Images with node
      uses: philips-software/docker-ci-scripts@v3.3.2
      with:
        dockerfile: 14/java
        image-name: node
        tags: 14-java 14.18-java 14.18.1-java 14.18.1-buster-slim-java
        push-branches: main

  build_node_lts:
    name: Build node lts
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - name: Build Docker Images with node
      uses: philips-software/docker-ci-scripts@v3.3.2
      with:
        dockerfile: lts/vanilla
        image-name: node
        tags: lts 16 16.13 16.13.0 16.13.0-buster
        push-branches: main
  
  build_node_lts_yarn2:
    name: Build node lts java
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - name: Build Docker Images with node and java
      uses: philips-software/docker-ci-scripts@v3.3.2
      with:
        dockerfile: lts/yarn2
        image-name: node
        tags: lts-yarn2 16-yarn2 16.13-yarn2 16.13.0-yarn2 16.13.0-buster-yarn2
        push-branches: main

  build_node_lts_java:
    name: Build node lts java
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - name: Build Docker Images with node and java
      uses: philips-software/docker-ci-scripts@v3.3.2
      with:
        dockerfile: lts/java
        image-name: node
        tags: lts-java 16-java 16.13-java 16.13.0-java 16.13.0-buster-java
        push-branches: main

  build_node_stable:
    name: Build node stable
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - name: Build Docker Images with node
      uses: philips-software/docker-ci-scripts@v3.3.2
      with:
        dockerfile: stable/vanilla
        image-name: node
        tags: latest stable 17 17.0 17.0.1 17.0.1-buster
        push-branches: main

  build_node_stable_yarn2:
    name: Build node with yarn 2
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - name: Build Docker Images with node
      uses: philips-software/docker-ci-scripts@v3.3.2
      with:
        dockerfile: stable/yarn2
        image-name: node
        tags: yarn2 stable-yarn2 17-yarn2 17.0-yarn2 17.0.1-yarn2 17.0.1-buster-yarn2
        push-branches: main

  build_node_stable_java:
    name: Build node stable with java
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - name: Build Docker Images with node
      uses: philips-software/docker-ci-scripts@v3.3.2
      with:
        dockerfile: stable/java
        image-name: node
        tags: java stable-java 17-java 17.0-java 17.0.1-java 17.0.1-buster-java
        push-branches: main

  test_latest_image:
    name: Test latest image
    runs-on: ubuntu-latest
    container: philipssoftware/node:latest
    if: github.ref == 'refs/heads/main'
    needs: build_node_stable
    steps:
    - uses: actions/checkout@v2.4.0
    - name: Test hello react app
      run: |
        npx create-react-app my-app
        cd my-app
        npm test
      env:
        CI: true

