on: [push]

name: Build Docker images

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: '${{ secrets.DOCKER_PASSWORD }}'
  DOCKER_ORGANIZATION: philipssoftware
  GITHUB_ORGANIZATION: philips-software

jobs:
  build_node_12:
    name: Build node 12
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker Images with node
      uses: philips-software/docker-ci-scripts@v3.2.1
      with:
        dockerfile: 12/vanilla
        image-name: node
        tags: 12 12.22 12.22.1 12.22.1-buster
        push-branches: main
  
  build_node_12_java:
    name: Build node 12 java
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker Images with node and java
      uses: philips-software/docker-ci-scripts@v3.2.1
      with:
        dockerfile: 12/java
        image-name: node
        tags: 12-java 12.22-java 12.22.1-java 12.22.1-buster-slim-java
        push-branches: main

  build_node_lts:
    name: Build node lts
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker Images with node
      uses: philips-software/docker-ci-scripts@v3.2.1
      with:
        dockerfile: lts/vanilla
        image-name: node
        tags: lts 14 14.16 14.16.1 14.16.1-buster
        push-branches: main

  build_node_lts_java:
    name: Build node lts with java
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker Images with node
      uses: philips-software/docker-ci-scripts@v3.2.1
      with:
        dockerfile: lts/java
        image-name: node
        tags: lts-java 14-java 14.16-java 14.16.1-java 14.16.1-buster-slim-java
        push-branches: main

  build_node_stable:
    name: Build node stable
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker Images with node
      uses: philips-software/docker-ci-scripts@v3.2.1
      with:
        dockerfile: stable/vanilla
        image-name: node
        tags: latest stable 15 15.14 15.14.0 15.14.0-buster
        push-branches: main

  build_node_stable_java:
    name: Build node stable with java
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker Images with node
      uses: philips-software/docker-ci-scripts@v3.2.1
      with:
        dockerfile: stable/java
        image-name: node
        tags: java stable-java 15-java 15.14-java 15.14.0-java 15.14.0-buster-java
        push-branches: main
