on: [push]

name: Build Docker images

jobs:
  build_node_12:
    name: Build node 12
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker Images with node
      uses: philips-software/docker-ci-scripts@v3.1.0
      with:
        dockerfile: 12/vanilla
        image-name: node
        tags: 12 12.19 12.19.0 12.19.0-stretch
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: '${{ secrets.DOCKER_PASSWORD }}'
        DOCKER_ORGANIZATION: philipssoftware
        GITHUB_ORGANIZATION: philips-software
  
  build_node_12_java:
    name: Build node 12 java
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker Images with node and java
      uses: philips-software/docker-ci-scripts@v3.1.0
      with:
        dockerfile: 12/java
        image-name: node
        tags: 12-java 12.19-java 12.19.0-java 12.19.0-stretch-java
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: '${{ secrets.DOCKER_PASSWORD }}'
        DOCKER_ORGANIZATION: philipssoftware
        GITHUB_ORGANIZATION: philips-software

  build_node_lts:
    name: Build node lts
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker Images with node
      uses: philips-software/docker-ci-scripts@v3.1.0
      with:
        dockerfile: lts/vanilla
        image-name: node
        tags: lts 14 14.15 14.15.0 14.15.0-stretch
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: '${{ secrets.DOCKER_PASSWORD }}'
        DOCKER_ORGANIZATION: philipssoftware
        GITHUB_ORGANIZATION: philips-software

  build_node_lts_java:
    name: Build node lts with java
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker Images with node
      uses: philips-software/docker-ci-scripts@v3.1.0
      with:
        dockerfile: lts/java
        image-name: node
        tags: lts-java 14-java 14.15-java 14.15.0-java 14.15.0-stretch-java
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: '${{ secrets.DOCKER_PASSWORD }}'
        DOCKER_ORGANIZATION: philipssoftware
        GITHUB_ORGANIZATION: philips-software

  build_node_stable:
    name: Build node stable
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker Images with node
      uses: philips-software/docker-ci-scripts@v3.1.0
      with:
        dockerfile: stable/vanilla
        image-name: node
        tags: latest stable 15 15.2 15.2.0 15.2.0-stretch
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: '${{ secrets.DOCKER_PASSWORD }}'
        DOCKER_ORGANIZATION: philipssoftware
        GITHUB_ORGANIZATION: philips-software

  build_node_stable_java:
    name: Build node stable with java
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker Images with node
      uses: philips-software/docker-ci-scripts@v3.1.0
      with:
        dockerfile: stable/java
        image-name: node
        tags: java stable-java 15-java 15.0-java 15.0.0-java 15.0.0-stretch-java
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: '${{ secrets.DOCKER_PASSWORD }}'
        DOCKER_ORGANIZATION: philipssoftware
        GITHUB_ORGANIZATION: philips-software
