on: [push]

name: Build Docker images

jobs:
  build_node_10:
    name: Build node 10
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker Images with node
      uses: philips-software/docker-ci-scripts@v3.0.0
      with:
        dockerfile: 10/vanilla
        image-name: node
        tags: 10 10.22 10.22.0 10.22.0-stretch
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: '${{ secrets.DOCKER_PASSWORD }}'
        DOCKER_ORGANIZATION: philipssoftware
        GITHUB_ORGANIZATION: philips-software
    - uses: philips-labs/tern-action@v1.1.0
      id: scan
      with:
        image: philipssoftware/node:10
        format: json
        output: node-10.json
    - uses: actions/upload-artifact@v2
      with:
        name: tern
        path: ${{ steps.scan.outputs.file }}
  
  build_node_10_java:
    name: Build node 10 java
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker Images with node and java
      uses: philips-software/docker-ci-scripts@v3.0.0
      with:
        dockerfile: 10/java
        image-name: node
        tags: 10-java 10.22-java 10.22.0-java 10.22.0-stretch-java
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: '${{ secrets.DOCKER_PASSWORD }}'
        DOCKER_ORGANIZATION: philipssoftware
        GITHUB_ORGANIZATION: philips-software

  build_node_lts:
    name: Build node lts
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker Images with node
      uses: philips-software/docker-ci-scripts@v3.0.0
      with:
        dockerfile: lts/vanilla
        image-name: node
        tags: lts 12 12.18 12.18.3 12.18.3-stretch
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: '${{ secrets.DOCKER_PASSWORD }}'
        DOCKER_ORGANIZATION: philipssoftware
        GITHUB_ORGANIZATION: philips-software

  build_node_lts_java:
    name: Build node lts with java
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker Images with node
      uses: philips-software/docker-ci-scripts@v3.0.0
      with:
        dockerfile: lts/java
        image-name: node
        tags: lts-java 12-java 12.18-java 12.18.3-java 12.18.3-stretch-java
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: '${{ secrets.DOCKER_PASSWORD }}'
        DOCKER_ORGANIZATION: philipssoftware
        GITHUB_ORGANIZATION: philips-software

  build_node_stable:
    name: Build node stable
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker Images with node
      uses: philips-software/docker-ci-scripts@v3.0.0
      with:
        dockerfile: stable/vanilla
        image-name: node
        tags: latest stable 14 14.11 14.11.0 14.11.0-stretch
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: '${{ secrets.DOCKER_PASSWORD }}'
        DOCKER_ORGANIZATION: philipssoftware
        GITHUB_ORGANIZATION: philips-software

  build_node_stable_java:
    name: Build node stable with java
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker Images with node
      uses: philips-software/docker-ci-scripts@v3.0.0
      with:
        dockerfile: stable/java
        image-name: node
        tags: java stable-java 14-java 14.11-java 14.11.0-java 14.11.0-stretch-java
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: '${{ secrets.DOCKER_PASSWORD }}'
        DOCKER_ORGANIZATION: philipssoftware
        GITHUB_ORGANIZATION: philips-software
