on: [push]

name: Build Docker images

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: '${{ secrets.DOCKER_PASSWORD }}'
  DOCKER_ORGANIZATION: philipssoftware
  GITHUB_ORGANIZATION: philips-software
  COSIGN_PRIVATE_KEY: '${{ secrets.COSIGN_PRIVATE_KEY }}'
  COSIGN_PASSWORD: '${{ secrets.COSIGN_PASSWORD }}'
  COSIGN_PUBLIC_KEY: '${{ secrets.COSIGN_PUBLIC_KEY }}'

jobs:
  build_node:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: Build node 12
            dockerfile: 12/vanilla
            tags: 12 12.22 12.22.8 12.22.8-buster
          - name: Build node 12 java
            dockerfile: 12/java
            tags: 12-java 12.22-java 12.22.8-java 12.22.8-buster-slim-java
          - name: Build node 14
            dockerfile: 14/vanilla
            tags: 14 14.18 14.18.2 14.18.2-buster
          - name: Build node 14 with java
            dockerfile: 14/java
            tags: 14-java 14.18-java 14.18.2-java 14.18.2-buster-slim-java
          - name: Build node lts stable
            dockerfile: lts/vanilla
            tags: latest stable lts 16 16.13 16.13.1 16.13.1-buster
          - name: Build node lts stable yarn 2 
            dockerfile: lts/yarn2
            tags: yarn2 stable-yarn2 lts-yarn2 16-yarn2 16.13-yarn2 16.13.1-yarn2 16.13.1-buster-yarn2
          - name: Build node lts stable java
            dockerfile: lts/java
            tags: java stable-java lts-java 16-java 16.13-java 16.13.1-java 16.13.1-buster-java
          - name: Build node 17
            dockerfile: current/vanilla
            tags: current 17 17.3 17.3.0 17.3.0-buster
          - name: Build node 17 with yarn 2
            dockerfile: current/yarn2
            tags: current-yarn2 17-yarn2 17.3-yarn2 17.3.0-yarn2 17.3.0-buster-yarn2
          - name: Build node 17 with java
            dockerfile: current/java
            tags: current-java 17-java 17.3-java 17.3.0-java 17.3.0-buster-java
    steps:
      - uses: actions/checkout@v2.4.0
      - name: ${{ matrix.name }}
        uses: philips-software/docker-ci-scripts@v4.1.2
        with:
          dockerfile: ${{ matrix.dockerfile }}
          image-name: node
          tags: ${{ matrix.tags }}
          sign: true
          slsa-provenance: true
          sbom: true

  test_latest_image:
    name: Test latest image
    runs-on: ubuntu-latest
    container: philipssoftware/node:latest
    if: github.ref == 'refs/heads/main'
    needs: build_node
    steps:
    - name: Test hello react app
      run: |
        npx create-react-app my-app
        cd my-app
        npm test
      env:
        CI: true
