on: [push]

name: Build Docker images

jobs:
  build_node_lts:
    name: Build node lts
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker Images with node
      uses: philips-software/docker-ci-scripts@v2.0.1
      with:
        dockerfile: 10
        image-name: node
        tags: lts 10 10.16 10.16.3 10.16.3-stretch
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: '${{ secrets.DOCKER_PASSWORD }}'
        DOCKER_ORGANIZATION: philipssoftware
        GITHUB_ORGANIZATION: philips-software
  
  build_node_lts_java:
    name: Build node lts java
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker Images with node and java
      uses: philips-software/docker-ci-scripts@v2.0.1
      with:
        dockerfile: 10/java
        image-name: node
        tags: lts-java 10-java 10.16-java 10.16.3-java 10.16.3-stretch-java
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: '${{ secrets.DOCKER_PASSWORD }}'
        DOCKER_ORGANIZATION: philipssoftware
        GITHUB_ORGANIZATION: philips-software

  build_node_stable:
    name: Build node stable 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker Images with node
      uses: philips-software/docker-ci-scripts@v2.0.1
      with:
        dockerfile: 12
        image-name: node
        tags: latest stable 12 12.9 12.9.0 12.9.0-stretch
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: '${{ secrets.DOCKER_PASSWORD }}'
        DOCKER_ORGANIZATION: philipssoftware
        GITHUB_ORGANIZATION: philips-software
  
  build_node_stable_java:
    name: Build node stable with java 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker Images with node
      uses: philips-software/docker-ci-scripts@v2.0.1
      with:
        dockerfile: 12/java
        image-name: node
        tags: java stable-java 12-java 12.9-java 12.9.0-java 12.9.0-stretch-java
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: '${{ secrets.DOCKER_PASSWORD }}'
        DOCKER_ORGANIZATION: philipssoftware
        GITHUB_ORGANIZATION: philips-software
