on: [push]

name: Build Docker images

jobs:
  build_node_stable:
    name: Build node stable
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker Images with node
      uses: philips-software/docker-ci-scripts@v3.1.0
      with:
        dockerfile: stable/vanilla
        image-name: node
        tags: 14.12 14.12.0 14.12.0-stretch
        push-branches: recreate-14-12
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: '${{ secrets.DOCKER_PASSWORD }}'
        DOCKER_ORGANIZATION: philipssoftware
        GITHUB_ORGANIZATION: philips-software

  build_node_stable_java:
    name: Build node stable with java
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker Images with node
      uses: philips-software/docker-ci-scripts@v3.1.0
      with:
        dockerfile: stable/java
        image-name: node
        tags: 14.12-java 14.12.0-java 14.12.0-stretch-java
        push-branches: recreate-14-12
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: '${{ secrets.DOCKER_PASSWORD }}'
        DOCKER_ORGANIZATION: philipssoftware
        GITHUB_ORGANIZATION: philips-software
