on: [push]

name: Build Docker images

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: '${{ secrets.DOCKER_PASSWORD }}'
  DOCKER_ORGANIZATION: philipssoftware
  GITHUB_ORGANIZATION: philips-software

jobs:
  build_node_12:
    name: Build node 12
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Build Docker Images with node
      uses: philips-software/docker-ci-scripts@v3.3.1
      with:
        dockerfile: 12/vanilla
        image-name: node
        tags: 12 12.22 12.22.6 12.22.6-buster
        push-branches: main
  
  build_node_12_java:
    name: Build node 12 java
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Build Docker Images with node and java
      uses: philips-software/docker-ci-scripts@v3.3.1
      with:
        dockerfile: 12/java
        image-name: node
        tags: 12-java 12.22-java 12.22.6-java 12.22.6-buster-slim-java
        push-branches: main

  build_node_lts:
    name: Build node lts
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Build Docker Images with node
      uses: philips-software/docker-ci-scripts@v3.3.1
      with:
        dockerfile: lts/vanilla
        image-name: node
        tags: lts 14 14.17 14.17.6 14.17.6-buster
        push-branches: main

  build_node_lts_java:
    name: Build node lts with java
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Build Docker Images with node
      uses: philips-software/docker-ci-scripts@v3.3.1
      with:
        dockerfile: lts/java
        image-name: node
        tags: lts-java 14-java 14.17-java 14.17.6-java 14.17.6-buster-slim-java
        push-branches: main

  build_node_15:
    name: Build node 15
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Build Docker Images with node
      uses: philips-software/docker-ci-scripts@v3.3.1
      with:
        dockerfile: 15/vanilla
        image-name: node
        tags: 15 15.14 15.14.0 15.14.0-buster
        push-branches: main
  
  build_node_15_java:
    name: Build node 15 java
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Build Docker Images with node and java
      uses: philips-software/docker-ci-scripts@v3.3.1
      with:
        dockerfile: 15/java
        image-name: node
        tags: 15-java 15.14-java 15.14.0-java 15.14.0-buster-java
        push-branches: main

  build_node_stable:
    name: Build node stable
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Build Docker Images with node
      uses: philips-software/docker-ci-scripts@v3.3.1
      with:
        dockerfile: stable/vanilla
        image-name: node
        tags: latest stable 16 16.9 16.9.1 16.9.1-buster
        push-branches: main

  build_node_yarn2:
    name: Build node with yarn 2
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Build Docker Images with node
      uses: philips-software/docker-ci-scripts@v3.3.1
      with:
        dockerfile: stable/yarn2
        image-name: node
        tags: yarn2 16-yarn2 16.9-yarn2 16.9.1-yarn2 16.9.1-buster-yarn2
        push-branches: main

  build_node_stable_java:
    name: Build node stable with java
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Build Docker Images with node
      uses: philips-software/docker-ci-scripts@v3.3.1
      with:
        dockerfile: stable/java
        image-name: node
        tags: java stable-java 16-java 16.9-java 16.9.1-java 16.9.1-buster-java
        push-branches: main

  test_latest_image:
    name: Test latest image
    runs-on: ubuntu-latest
    container: philipssoftware/node:latest
    if: github.ref == 'refs/heads/main'
    needs: build_node_stable
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Test hello react app
      run: |
        npx create-react-app my-app
        cd my-app
        npm test
      env:
        CI: true

