on: [push]
name: Build Docker images
env:
  REGISTRY_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  REGISTRY_TOKEN: '${{ secrets.DOCKER_PASSWORD }}'
  DOCKER_ORGANIZATION: philipssoftware
  GITHUB_ORGANIZATION: philips-software
  KEYLESS: true
jobs:
  build_node:
    permissions:
      packages: write
      id-token: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: Build node 14
            dockerfile: 14/vanilla
            tags: 14 14.21 14.21.3 14.21.3-buster
          - name: Build node 14 with java
            dockerfile: 14/java
            tags: 14-java 14.21-java 14.21.3-java 14.21.3-buster-slim-java

          - name: Build node 16
            dockerfile: 16/vanilla
            tags: 16 16.19 16.19.1 16.19.1-buster
          - name: Build node 16 yarn 2
            dockerfile: 16/yarn2
            tags: 16-yarn2 16.19-yarn2 16.19.1-yarn2 16.19.1-buster-yarn2
          - name: Build node 16 java
            dockerfile: 16/java
            tags: 16-java 16.19-java 16.19.1-java 16.19.1-buster-java

          - name: Build node LTS / stable 18
            dockerfile: lts/vanilla
            tags: stable lts latest 18 18.15 18.15.0 18.15.0-buster
          - name: Build node LTS / stable 18 with yarn 2
            dockerfile: lts/yarn2
            tags: yarn2 stable-yarn2 lts-yarn2 latest-yarn2 18-yarn2 18.15-yarn2 18.15.0-yarn2 18.15.0-buster-yarn2
          - name: Build node LTS / stable 18 with java
            dockerfile: lts/java
            tags: java stable-java lts-java latest-java 18-java 18.15-java 18.15.0-java 18.15.0-buster-java

          - name: Build node current 19
            dockerfile: current/vanilla
            tags: current 19 19.8 19.8.1 19.8.1-buster
          - name: Build node current 19 with yarn 2
            dockerfile: current/yarn2
            tags: current-yarn2 19-yarn2 19.8-yarn2 19.8.1-yarn2 19.8.1-buster-yarn2
          - name: Build node current 19 with java
            dockerfile: current/java
            tags: current-java 19-java 19.8-java 19.8.1-java 19.8.1-buster-java
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # ratchet:actions/checkout@v3
      - name: ${{ matrix.name }}
        uses: philips-software/docker-ci-scripts@d0045b844f08b0dcb4c62bd4acf6c36877404dae # ratchet:philips-software/docker-ci-scripts@v5.1.0
        with:
          dockerfile: ${{ matrix.dockerfile }}
          image-name: node
          tags: ${{ matrix.tags }}
          sign: true
          slsa-provenance: true
          sbom: true
  test_latest_image:
    name: Test latest image
    runs-on: ubuntu-latest
    container: philipssoftware/node:latest
    if: github.ref == 'refs/heads/main'
    needs: build_node
    steps:
      - name: Test hello react app
        run: |
          npx create-react-app my-app
          cd my-app
          npm test
        env:
          CI: true
