on:
  schedule:
    - cron: '14 15 * * 1'
  workflow_dispatch:

name: Check vulnerabilities 

permissions: 
  id-token: write

jobs:
  check:
    name: Check Vulnerabities
    uses: philips-software/docker-ci-scripts/workflows/check_vulnerabilities/check_vulnerabilities.yaml@main
    with:
      image: philipssoftware/node:18.10.0-buster

