name: Check vulnerabilities 

on:
  schedule:
    - cron: '14 15 * * 1'
  workflow_dispatch:

permissions: 
  id-token: write

jobs:
  check:
    name: Check Vulnerabities
    uses: philips-software/docker-ci-scripts/.github/workflows/check-vulnerabilities.yaml@check-vulnerabilities
    with:
      image: philipssoftware/node:18.10.0-buster

